# -*- coding: utf-8 -*-
"""review sentiment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15j4_xlMJHkvvCiieCaa5zz0x7wiP82Nz
"""


import pandas as pd
import streamlit as st
import time
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from PIL import Image   ## For image
from io import StringIO  ## for text input and output from the web app

model = SentimentIntensityAnalyzer()
def predict(string):
    ss = model.polarity_scores(string)
    
    
    #print("{:.0%}".format(ss["compound"]), end=' ')
        
    if ss["compound"]>0:
        return(str("{:.0%}".format(ss["compound"]))+" "+"positive")
          
    elif ss["compound"]<0:
          return(str("{:.0%}".format(ss["compound"]))+" "+"negative")
          
    else:
        return("neutral")

def run():
    
    st.sidebar.info('You can either enter your review online in the textbox or upload a txt file')
    st.set_option('deprecation.showfileUploaderEncoding', False)
    add_selectbox = st.sidebar.selectbox("How would you like to comment?", ("Online", "Txt file"))
    st.title("Predicting trafic review")
    st.header('Tell us your opinion about this WebApp')
    if add_selectbox == "Online":
        text1 = st.text_area('Enter text')
        output = ""
        if st.button("review prediction"):
            output = predict(text1)
            st.success(f"Thank you! your review is {output}")
            st.balloons()
    elif add_selectbox == "Txt file":
          output = ""
          file_buffer = st.file_uploader("Upload text file for new review", type=["txt"])
          if st.button("Predict"):
             text_review = file_buffer.read()

        


if __name__ == "__main__":
  run()
